import React, { useRef, useState } from "react";
import "./Upload.css";
import app from "../firebase";
import { getDatabase, set, push, ref } from "firebase/database";

const Upload = () => {
  const [img, setImg] = useState();
  const [state, setState] = useState({
    id: "",
    link: "",
    title: "",
    skills_used: "",
  });

   // Ref for the file input
   const fileInputRef = useRef(null);

  //image handler
  const handleImage = (file) => {
    const fileReader = new FileReader();
    fileReader.addEventListener("load", () => {
      setImg(fileReader.result);
    });
    fileReader.readAsDataURL(file);
  };

  const changeHandler = (e) => {
    let { name, value } = e.target;
    // console.log(name, ":", value);
    setState({ ...state, [name]: value });
  };

  const submitHandler = async (e) => {
    e.preventDefault();
    const db = getDatabase(app);

    // Generate a new unique reference with push()
    const newDocRef = push(ref(db, "data"));

    // Get the key generated by push()
    const newId = newDocRef.key;

    set(newDocRef, {
      id: newId,
      link: state.link,
      title: state.title,
      skills_used: state.skills_used,
      image: img,
    })
      .then(() => {
        alert("Data Saved Successfully!");

        //clear data
        setState({
          id: "",
          link: "",
          title: "",
          skills_used: "",
        });

        // Clear the image preview
        setImg("");
        // Clear the file input
        if (fileInputRef.current) {
          fileInputRef.current.value = "";
        }
      })
      .catch((err) => {
        alert(err.message);
      });
  };

  return (
    <div className="upload_css">
      <div className="upload_base_css_1" onSubmit={submitHandler}>
        <form className="upload_base_css">
          <h1>Upload Your Project</h1>
          <div className="link_css">
            <label>Link</label>
            <input placeholder="Enter the link of your website" value={state.link} name="link" style={{ width: "100%" }} required onChange={changeHandler} />
          </div>
          <div className="title_css">
            <label>Title</label>
            <input type="text" placeholder="Enter the title of the Website" value={state.title} name="title" style={{ width: "100%" }} required onChange={changeHandler} />
          </div>
          <div className="skills_css">
            <label>Skills</label>
            <input placeholder="Enter the skills used." name="skills_used" value={state.skills_used} style={{ width: "100%" }} required onChange={changeHandler} />
          </div>
          <div className="img_css">
            <label>Image</label>
            <input
              type="file"
              name="image"
              alt=""
              ref={fileInputRef}
              style={{ width: "100%" }}
              required
              onChange={(event) => {
                handleImage(event.target.files[0]);
              }}
            />
          </div>
          <div>
            <button>Submit</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Upload;
